Server:
  port: 8082

Spring:

  data:
    mongodb:
      uri: {MONGODB_URL}
      database: fitnessactivity

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/


rabbitmq:
  exchange:
    name:
      fitness.exchange
  queue:
    name:
      activity.queue
  routing:
    key:
      activity.tracking