Server:
  port: 8081

Spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/fitness_user_db
    username: root
    password: root12345

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
